### ISSUE TITLE
Compile problem---SDL_pcf not found

### ISSUE THREAD

**Issue by andrewrunxiyu** [sam-itt/sofis#20]
In many files, there is:
```c
#include "SDF_pcf.h"
```
When I ran `make`, it complains about not having that header file. They're in double quotes, and not in the project directory. `/usr/include/SDL` doesn't include anything related to `pcf` either, (I have the full SDL installation on Arch Linux), so changing " to <> won't really help, I thought.

This left me unable to compile. Any ideas? Thanks :D

**Comment by andrewrunxiyu** [comment]
Solution: Carefully read the build guide.
Sorry!

**Comment by sam-itt** [comment]
Glad you got it working !
